channels:
  - defaults
  - bioconda
  - conda-forge

dependencies:
  - python = 3.8.6
  - snakemake = 5.28.0
  - jinja2 = 2.11.2
  - networkx = 2.5
  - bcftools = 1.11
  - samtools = 1.11
  - bwa = 0.7.17
  - pysam = 0.16.0.1
  - cutadapt = 3.0
  - bedtools = 2.29.2
  - STAR = 2.7.6a
  - trim-galore = 0.6.6
  - pip = 20.2.4
  - pybedtools = 0.8.1
  - numpy = 1.19.4
  - pandas = 1.1.4
  - numpydoc = 1.1.0
  - sphinx = 3.3.1
  - matplotlib = 3.3.3
  - docutils = 0.16
  - sphinx-releases = 1.6.1
