import os

from setuptools import setup, find_packages

# determine version string
VERSION = '2.0.0'
ISRELEASED = False

if not ISRELEASED:
    VERSION = '{}-dev'.format(VERSION)

# store version to file
open('iCount/_version.py', 'w').write(
    "# THIS FILE WAS GENERATED BY SETUP.PY\n"
    "__version__ = '{}'\n".format(VERSION))

# read contents of README and CHANGES
here = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(here, 'README.md')) as f:
    README = f.read()

setup(
    name='iCount',
    version=VERSION,
    description='Computational pipeline for analysis of iCLIP data',
    long_description=README,
    classifiers=[
        'Development Status :: 4 - Beta',
        'Topic :: Scientific/Engineering :: Bio-Informatics',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'Operating System :: POSIX',
        'Programming Language :: Python',
    ],
    author='University of Ljubljana, Bioinformatics Laboratory',
    author_email='tomazc@gmail.com',
    url='',
    keywords='iCLIP protein-RNA',
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires={
        'numpy',
        'pandas',
        'cutadapt==1.10',
        'pysam',
        'pybedtools',
        'numpydoc',
        'sphinx>=1.4',
    },
    extras_require={
        'docs': [
            'docutils',
            'sphinx>=1.4',
            'sphinxcontrib-fulltoc>=0.1.9',
        ],
        'tests': [
            'pylint',
            'pytest-cov',
            'pycodestyle',
            'pydocstyle',
            'coverage',
            'tox',
        ],
    },
    test_suite='iCount.tests.suite',
    entry_points={
        'console_scripts': [
            'iCount = iCount.cli:main',
        ],
    },
)
